CREATE TABLE project (
    ID INTEGER not null PRIMARY KEY,
    code1 VARCHAR(100),
    code2 VARCHAR(100),
    launch_from DATETIME,
    launch_to DATETIME,
    title VARCHAR(255),
    short_title VARCHAR(255),
    web_content TEXT,
    business VARCHAR(100),
    country VARCHAR(100),
    status VARCHAR(100),
    amount1 DOUBLE,
    amount2 DOUBLE,
    amount3 DOUBLE,
    amount4 DOUBLE,
    amount5 DOUBLE,
    quantity1 INTEGER,
    quantity2 INTEGER,
    quantity3 INTEGER,
    quantity4 INTEGER,
    flag1 BOOLEAN,
    flag2 BOOLEAN,
    flag3 BOOLEAN,
    flag4 BOOLEAN,
    flag5 BOOLEAN,
    flag6 BOOLEAN
);

